[package]
name = "simulated_pixel_game_engine"
version = "0.1.0"
authors = ["Christopher Lang <christopher-d-lang@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.16.1"